algoritmo "exerc2"
// Função :
// Autor :
// Data : 24/7/2008
// Página 42
var
financiamento:real
salario:real
teste:real
inicio
escreva("Insira o seu sálario: ")
leia(salario)
escreva("Insira quanto quer de financiamento: ")
leia(financiamento)
teste <- 5 * salario
se financiamento <= teste entao
escreval("Financiamento concedido")
senao
escreval("Financiamento negado")
fimse
escreva("Obrigado por nos consultar")
fimalgoritmo
