algoritmo "exerc3"
// Função :
// Autor :
// Data : 24/7/2008
// Página 43
var
nota:inteiro
inicio
escreval("Insira a nota do aluno: ")
leia(nota)
escolha nota
caso 1,2,3
   escreva("Conceito E")
caso 3, 4, 5
   escreva("Conceito D")
caso 6, 7
   escreva("Conceito C")
caso 8, 9
   escreva("Conceito B")
caso 10
   escreva("Conceito A")
outrocaso
   escreva("Nota incorreta, tente novamente")
fimescolha
fimalgoritmo
